NewsStudyRostelecom/NewsStudyRostelecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import main.views as main_views
handler404 = main_views.custom_404
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('news/', include('news.urls')),
    path('users/', include('users.urls')),
    path('home/', include('home.urls')),
    #htpp://127.0.0.1:8000/
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns=[
        path('__debug/__', include(debug_toolbar.urls)),
    ]+ urlpatterns

    urlpatterns+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования новостей"
admin.site.index_title = "Новости нашего города"
admin.site.index_template = 'main/custom_admin.html'

NewsStudyRostelecom/home/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('demoform/',views.demoform),
    path('showlastmodel/',views.showlastmodel),
    path('', views.index, name='demo'),
]

NewsStudyRostelecom/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
urlpatterns = [
    path('', views.index, name='user_index'),
    path('contact_page',views.contact_page,name='contact_page'),
    path('registration',views.registration,name='registration'),
    path('login', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(
        template_name='users/logout.html'), name='logout'),
    path('profile',views.profile,name='profile'),
    path('profile/update', views.profile_update, name='profile_update'),
    path('password', views.password_update, name='password'),
    path('favorites/<int:id>', views.add_to_favorites, name='favorites'),
    path('mynewslist',views.my_news_list,name='my_news_list'),
]

NewsStudyRostelecom/news/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from django.db.models import Count

class Tag(models.Model):
    title = models.CharField(max_length=80)
    status = models.BooleanField(default=True)
    def __str__(self):
        return self.title

    def tag_count(self):
        count = self.article_set.count()
        #комментарий: когда мы работаем со связанными объектами (foreign_key, m2m, один к одному),
        #мы можем обращаться к связанным таблицам при помощи синтаксиса:
        #связаннаяМодель_set и что-то делать с результатами. В этом примере - мы используем связанные article
        #и вызываем метод count
        return count

    class Meta:
        ordering = ['title','status']
        verbose_name= 'Тэг'
        verbose_name_plural='Тэги'

import datetime
class PublishedToday(models.Manager):
    def get_queryset(self):
        return super(PublishedToday,self).get_queryset().filter(date__gte=datetime.date.today())

class Article(models.Model):
    categories = (('E','Economics'),
                  ('S','Science'),
                  ('IT','IT'))
    #поля                           #models.CASCADE SET_DEFAULT
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField('Название',max_length=50,default='')
    anouncement = models.TextField('Аннотация',max_length=250)
    text = models.TextField('Текст новости')
    date = models.DateTimeField('Дата публикации',auto_now=True)
    category = models.CharField(choices=categories, max_length=20,verbose_name='Категории')
    tags = models.ManyToManyField(to=Tag, blank=True)
    slug = models.SlugField()
    objects = models.Manager()
    published = PublishedToday()

    #методы моделей
    def __str__(self):
        return f'{self.title} от: {str(self.date)[:16]}'

    def get_absolute_url(self):
        return f'/news/show/{self.id}'
    #метаданные модели


    def tag_list(self):
        s = ''
        for t in self.tags.all():
            s+=t.title+' '
        return s

    def image_tag(self):
        image = Image.objects.filter(article=self)
        print('!!!!',image)
        if image:
            return mark_safe(f'<img src="{image[0].image.url}" height="50px" width="auto" />')
        else:
            return '(no image)'


    def get_views(self):
        return self.views.count()

    class Meta:
        ordering = ['title','date']
        verbose_name= 'Новость'
        verbose_name_plural='Новости'


class Image(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(upload_to='article_images/') #лучше добавить поле default !!!

    def __str__(self):
        return self.title

    def image_tag(self):
        if self.image is not None:
            return mark_safe(f'<img src="{self.image.url}" height="50px" width="auto" />')
        else:
            return '(no image)'

class ViewCount(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,
                                related_name='views')
    ip_address = models.GenericIPAddressField()
    view_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('-view_date',)
        indexes = [models.Index(fields=['-view_date'])]

    def __str__(self):
        return self.article.title

NewsStudyRostelecom/users/models.py
from django.db import models
from django.contrib.auth.models import User

class Account(models.Model):
    gender_choices= (('M','Male'),
                     ('F','Female'),
                     ('N/A','Not answered'))
    user = models.OneToOneField(User,on_delete=models.CASCADE,
                                primary_key=True)
    nickname = models.CharField(max_length=100)
    birthdate = models.DateField(null=True)
    gender = models.CharField(choices=gender_choices,max_length=20,null=True)
    account_image = models.ImageField(default='default.jpg',
                                      upload_to='account_images')
    address = models.CharField(max_length=100,null=True)
    vk = models.CharField(max_length=100,null=True)
    instagram = models.CharField(max_length=100,null=True)
    telegram = models.CharField(max_length=100,null=True)
    phone = models.CharField(max_length=20,null=True)
    #pip install pillow в терминале если нет библиотеки

    def __str__(self):
        return f"{self.user.username}'s account"
    class Meta:
        ordering = ['user']
        verbose_name = 'Профиль'
        verbose_name_plural ='Профили'


from news.models import Article
class FavoriteArticle(models.Model):
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    article = models.ForeignKey(Article,on_delete=models.SET_NULL,null=True)
    create_at=models.DateTimeField(auto_now_add=True)

NewsStudyRostelecom/users/forms.py
from django import forms
from .validators import russian_email
from django.core.validators import MinLengthValidator

from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, EmailInput, FileInput, Select


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        widgets = {'username': TextInput({'class': 'textinput form-control',
                                          'placeholder': 'username'}),
                   'email': EmailInput({'class': 'textinput form-control',
                                        'placeholder': 'email'}),
                   'first_name': TextInput({'class': 'textinput form-control',
                                            'placeholder': 'First name'}),
                   'last_name': TextInput({'class': 'textinput form-control',
                                           'placeholder': 'Last name'}),
                   }


from .models import Account
class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['phone', 'address','vk','instagram','telegram', 'account_image']
        widgets = {'phone': TextInput({'class': 'textinput form-control',
                                       'placeholder': 'phone number'}),
                   'address': TextInput({'class': 'textinput form-control',
                                         'placeholder': 'address'}),
                   'vk': TextInput({'class': 'textinput form-control',
                                      'placeholder': 'vk'}),
                   'instagram': TextInput({'class': 'textinput form-control',
                                         'placeholder': 'instagram'}),
                   'telegram': TextInput({'class': 'textinput form-control',
                                           'placeholder': 'telegram'}),
                   'account_image': FileInput({'class': 'form-control',
                                       'placeholder': 'image'})
                   }

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100,
                           validators = [MinLengthValidator(2)],
                           initial='Имя')
    email = forms.EmailField(validators=[russian_email])
    message = forms.CharField(widget=forms.TextInput, disabled=False)
    demo = forms.BooleanField(required = False, help_text='Текст-подсказка',
                              label='Вам нравится?',
                              initial=True)

NewsStudyRostelecom/users/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, HttpResponse
from .models import *
from .forms import *

from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import Group




def profile(request):
    context = dict()
    return render(request,'users/profile.html',context)

from .forms import AccountUpdateForm, UserUpdateForm

from django.contrib.auth.decorators import login_required
from news.models import Article
@login_required
def add_to_favorites(request, id):
    article = Article.objects.get(id=id)
    #проверям есть ли такая закладка с этой новостью
    bookmark = FavoriteArticle.objects.filter(user=request.user.id,
                                              article=article)
    if bookmark.exists():
        bookmark.delete()
        messages.warning(request,f"Новость {article.title} удалена из закладок")
    else:
        bookmark = FavoriteArticle.objects.create(user=request.user, article=article)
        messages.success(request,f"Новость {article.title} добавлена в закладки")
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def profile_update(request):
    user = request.user
    account = Account.objects.get(user=user)
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=user)
        account_form = AccountUpdateForm(request.POST, request.FILES, instance=account)
        if user_form.is_valid() and account_form.is_valid():
            user_form.save()
            account_form.save()
            messages.success(request,"Профиль успешно обновлен")
            return redirect('profile')
        else:
            pass
    else:
        context = {'account_form':AccountUpdateForm(instance=account),
                   'user_form':UserUpdateForm(instance=user)}
    return render(request,'users/edit_profile.html',context)

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
def password_update(request):
    user = request.user
    form = PasswordChangeForm(user,request.POST)
    if request.method == 'POST':
        if form.is_valid():
            password_info = form.save()
            update_session_auth_hash(request,password_info)
            messages.success(request,'Пароль успешно изменен')
            return redirect('profile')

    context = {"form": form}
    return render(request,'users/edit_password.html',context)


def registration(request):
    if request.method=='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save() #появляется новый пользователь
            category = request.POST['account_type']
            if category == 'author':
                group = Group.objects.get(name='Actions Required')
                user.groups.add(group)
            else:
                group = Group.objects.get(name='Reader')
                user.groups.add(group)
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            account = Account.objects.create(user=user,nickname=user.username)

            #!!!не аутентифицируется - нужно доделать
            #from django.contrib.auth import authenticate, login
            user = authenticate(username=username,password=password)
            login(request,user)
            messages.success(request,f'{username} был зарегистрирован!')

            return redirect('home')
    else:
        form = UserCreationForm()
    context = {'form':form}
    return render(request,'users/registration.html',context)


def contact_page(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            print('Сообщение отправлено', form.cleaned_data)
        else:
            print(form.errors)
    else:
        form = ContactForm()
        form.name='Любимый клиент'
    context = {'form': form}
    return render(request,'users/contact_page.html',context)


def index(request):
    print(request.user,request.user.id)
    user_acc = Account.objects.get(user=request.user)
    print(user_acc.birthdate,user_acc.gender)
    return HttpResponse('Приложение Users')


from django.core.paginator import Paginator
def my_news_list(request):
    categories = Article.categories #создали перечень категорий
    author = User.objects.get(id=request.user.id) #создали перечень авторов
    articles = Article.objects.filter(author=author)
    if request.method == "POST":
        selected_category = int(request.POST.get('category_filter'))
        if selected_category != 0: #фильтруем найденные результаты по категориям
            articles = articles.filter(category__icontains=categories[selected_category-1][0])
    else: #если страница открывется впервые
        selected_category = 0
    total = len(articles)
    p = Paginator(articles,2)
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    context = {'articles': page_obj, 'total':total,
               'categories':categories,'selected_category': selected_category}

    return render(request,'users/my_news_list.html',context)

NewsStudyRostelecom/users/templates/users/contact_page.html
{% extends 'main/base_template.html' %}
{% load static %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% block title %} Страница обратной связи {% endblock %}

{% block content %}
        <div class="row">
            <div class="text-center" style="margin-top:30px;">
                    <h1 >Страница обратной связи</h1>
            <form method="post" class="contact_form">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success" value = "Отправить">
            </form>
            </div>

        </div>
{% endblock %}

NewsStudyRostelecom/users/templates/users/edit_password.html
{% extends 'main/base_template.html' %}
{% load static %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}

{% block title %} Изменение пароля{% endblock %}


{% block content %}
        <div class="row">
            <div class="text-center" style="margin-top:30px;">
                    <h1 > Изменение пароля аккаунта </h1>
                    <form method="post" class="contact-form">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class='btn btn-success' type="submit" value="Обновить">
                        <a class='btn btn-warning' href="{% url 'profile' %}">Отмена</a>
                    </form>
            </div>
        </div>
{% endblock %}

NewsStudyRostelecom/users/templates/users/edit_profile.html
{% extends 'main/base_template.html' %}
{% load static %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}

{% block title %} Редактирования профиля {% endblock %}
{% block sidebar %} {% include 'users/user_panel.html' %} {% endblock %}

{% block content %}
<div class="row">
    <div class="text-center" style="margin-top:30px;">
        <h2>Редактирования профиля {{ request.user.username }}</h2>
        <br>
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="{{ request.user.account.account_image.url }}" alt="{{ request.user.username }}"
                                 class="rounded-circle" width="150">
                            {{ account_form.account_image }}
                            <div class="mt-3">
                                <h4> {{ user_form.username }}</h4>
                                <p class="text-secondary mb-1"> {% if request.user.is_staff %} Автор {% endif %}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card mt-3">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">
                                <img src="{% static 'main/img/vk.png' %}" style="height:24px; width:auto;">
                            </h6>
                            <span class="text-secondary"> {{ account_form.vk }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                     fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                     stroke-linejoin="round"
                                     class="feather feather-instagram mr-2 icon-inline text-danger">
                                    <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                                    <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                                    <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
                                </svg>
                            </h6>
                            <span class="text-secondary"> {{ account_form.instagram }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">
                                <img src="{% static 'main/img/telegram.png' %}" style="height:24px; width:auto;">
                            </h6>
                            <span class="text-secondary">{{ account_form.telegram }}</span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Full Name</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{ user_form.username }}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{ user_form.email }}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Phone</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{ account_form.phone }}
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Address</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                                {{ account_form.address }}
                        </div>
                    </div>
                    <hr>

                    <div class="text-center">
                        <button class="btn btn-outline-success" style="margin-bottom:15px;"
                           href="{% url 'profile' %}"> Сохранить </button>
                        <a class="btn btn-outline-danger" style="margin-bottom:15px;"
                           href="{% url 'password' %}"> Изменить пароль </a>
                    </div>

                </div>
            </div>
        </div>
        </form>
    </div>
</div>

</div>

{% endblock %}

NewsStudyRostelecom/users/templates/users/index.html
{% extends 'main/base_template.html' %}
{% load static %}
{% load bootstrap5 %}
{% block title %} Главная страница {% endblock %}

{% block content %}
        <div class="row">
            <div class="text-center" style="margin-top:30px;">
                    <h1 >Главная страница</h1>
            </div>

             <div class="single_news">
                <div class="p-4 p-md-5 text-white rounded bg-dark" >
                        <div class="col-md-6 px-0">
                          <h1 class="display-4 fst-italic"> {{ article.title }}</h1>
                          <p class="lead my-3">{{ article.anouncement }}</p>
                          <p class="lead mb-0"><a href="{{ article.get_absolute_url }}" class="text-white fw-bold">Полный текст...</a></p>
                        </div>
                  </div>
            </div>
        </div>
{% endblock %}

NewsStudyRostelecom/users/templates/users/login.html
{% extends 'main/base_template.html' %}
{% load static %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% block title %} Вход в аккаунт {% endblock %}

{% block content %}
        <div class="row">
            <div class="text-center" style="margin-top:30px;">
                    <h1 >Войти в аккаунт</h1>
            <form method="post" class="contact_form">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success" value = "Войти">
                <div class="border-top pt-3">
                    <small class="text-muted"> Нужен аккаунт?</small>
                           <a class="ml-2" href="{% url 'registration' %}">Зарегистрироваться</a>
                </div>
            </form>
            </div>

        </div>
{% endblock %}

NewsStudyRostelecom/users/templates/users/my_favorites.html
{% extends 'main/base_template.html' %}
{% load static %}
{% load bootstrap5 %}
{% block title %} Избранное {% endblock %}
{% block sidebar %} {% include 'users/user_panel.html' %} {% endblock %}

{% block content %}

<div class="content_center">
    {% if articles|length  != 0 %}
    <div class="row">
        <label><h1> Фильтры: (Всего :{{ total }} результатов) </h1>
            <form method="post">
                {% csrf_token %}
                <div class="form-group col-11">
                    <select class="form-select" name="category_filter" style="width:40%">
                        <option value="0">Все категории</option>
                        {% for c in categories %}
                        <option value="{{ forloop.counter }}" {% if selected_category == forloop.counter %} selected {% endif %}> {{ c.1 }}
                        </option>
                        {% endfor %}
                    </select>
                    <input type="submit" class="btn btn-success" value="Применить">
                </div>
            </form>
        </label>
    </div>
        <br>
<!--    ниже пагинатор -->
    {% if total > 1 %}
    <div class="row">
        <nav aria-label="Page navigation example">
          <ul class="pagination">
              {% if articles.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">Previous</a></li>
              {% endif %}
              {% for p in articles.paginator.page_range %}
                {% if articles.number == p %}
                    <li class="page-item"><p class="page-link" style="color:black;"> {{ p }}</p></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ p }}"> {{ p }}</a></li>
                {% endif %}
              {% endfor %}
              {% if articles.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">Next</a></li>
              {% endif %}
          </ul>
        </nav>
    </div>
    {% endif %}
    <div class="row">
        {% for article in articles %}
            <div class="single_news">
            <div class="p-4 p-md-5 text-white rounded bg-dark">
                <div class="row">
                    <div class="col-md-{% if article.image_set.all %}6{% else %}12 {% endif %} px-0">
                        <h1 class="display-4 fst-italic"> {{ article.title }}</h1>
                        <p class="lead my-3">{{ article.anouncement }}</p>
                        <p class="lead mb-0"><a href="{% url 'news_detail' article.pk %}" class="text-white fw-bold">Полный текст..</a></p>
                        <p><small>Просмотры: {{ article.get_views }}</small></p>
                        <a class="btn btn-success" href="{% url 'favorites' article.pk %}"><i class="fa fa-bookmark">В избранное</i></a>
                    </div>
                    {% if article.image_set.all %}
                    <div class="col-md-6 px-0">
                        <img src="{{ article.image_set.all.0.image.url }}"
                             style="width:100%; height:auto; border-radius:5px;">
                        <br>
                        <br>
                        <img src="{{ article.image_set.all.1.image.url }}"
                             style="width:100%; height:auto; border-radius:5px;">
                    </div>
                    {% endif %}
                </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="content_center">
    <div class="row">
        <h1> Вы еще не написали ни одной новости. </h1>
            <a class="ml-2" href="{% url 'create_article' %}"><h1> Хотите создать первую?</h1></a>

    </div>
</div>
{% endif %}
{% endblock %}

NewsStudyRostelecom/users/templates/users/my_news_list.html
{% extends 'main/base_template.html' %}
{% load static %}
{% load bootstrap5 %}
{% block title %} Мои статьи {% endblock %}
{% block sidebar %} {% include 'users/user_panel.html' %} {% endblock %}

{% block content %}

<div class="content_center">
    {% if articles|length  != 0 %}
    <div class="row">
        <label><h1> Фильтры: (Всего :{{ total }} результатов) </h1>
            <form method="post">
                {% csrf_token %}
                <div class="form-group col-11">
                    <select class="form-select" name="category_filter" style="width:40%">
                        <option value="0">Все категории</option>
                        {% for c in categories %}
                        <option value="{{ forloop.counter }}" {% if selected_category == forloop.counter %} selected {% endif %}> {{ c.1 }}
                        </option>
                        {% endfor %}
                    </select>
                    <input type="submit" class="btn btn-success" value="Применить">
                </div>
            </form>
        </label>
    </div>
        <br>
<!--    ниже пагинатор -->
    {% if total > 1 %}
    <div class="row">
        <nav aria-label="Page navigation example">
          <ul class="pagination">
              {% if articles.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">Previous</a></li>
              {% endif %}
              {% for p in articles.paginator.page_range %}
                {% if articles.number == p %}
                    <li class="page-item"><p class="page-link" style="color:black;"> {{ p }}</p></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ p }}"> {{ p }}</a></li>
                {% endif %}
              {% endfor %}
              {% if articles.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">Next</a></li>
              {% endif %}
          </ul>
        </nav>
    </div>
    {% endif %}
    <div class="row">
        {% for article in articles %}
            <div class="single_news">
            <div class="p-4 p-md-5 text-white rounded bg-dark">
                <div class="row">
                    <div class="col-md-{% if article.image_set.all %}6{% else %}12 {% endif %} px-0">
                        <h1 class="display-4 fst-italic"> {{ article.title }}</h1>
                        <p class="lead my-3">{{ article.anouncement }}</p>
                        <p class="lead mb-0"><a href="{% url 'news_detail' article.pk %}" class="text-white fw-bold">Полный текст..</a></p>
                        <p><small>Просмотры: {{ article.get_views }}</small></p>
                        <a class="btn btn-success" href="{% url 'favorites' article.pk %}"><i class="fa fa-bookmark">В избранное</i></a>
                    </div>
                    {% if article.image_set.all %}
                    <div class="col-md-6 px-0">
                        <img src="{{ article.image_set.all.0.image.url }}"
                             style="width:100%; height:auto; border-radius:5px;">
                        <br>
                        <br>
                        <img src="{{ article.image_set.all.1.image.url }}"
                             style="width:100%; height:auto; border-radius:5px;">
                    </div>
                    {% endif %}
                </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="content_center">
    <div class="row">
        <h1> Вы еще не написали ни одной новости. </h1>
            <a class="ml-2" href="{% url 'create_article' %}"><h1> Хотите создать первую?</h1></a>

    </div>
</div>
{% endif %}
{% endblock %}